# fly.toml app configuration file generated for oprec-webdev-ristek24 on 2025-03-11T01:08:36+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oprec-webdev-ristek24'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  FRONTEND_URL = 'https://oprec-webdev-ristek24.netlify.app'
  GITHUB_REDIRECT_URI = 'https://oprec-webdev-ristek24.fly.dev/v1/auth/github/callback'
  POST_LOGIN_REDIRECT_URI = 'https://oprec-webdev-ristek24.netlify.app/user'
  SERVER_PORT = '3000'
  SESSION_POOLING_INTERVAL = '120'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
